# Scrape bitcoin trends data from Google trends

In [ ]:
# install pytrends packages
!pip install pytrends

Requirement already satisfied: pytrends in /usr/local/lib/python3.7/dist-packages (4.7.3)
Requirement already satisfied: pandas>=0.25 in /usr/local/lib/python3.7/dist-packages (from pytrends) (1.1.5)
Requirement already satisfied: lxml in /usr/local/lib/python3.7/dist-packages (from pytrends) (4.2.6)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from pytrends) (2.23.0)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25->pytrends) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25->pytrends) (2018.9)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25->pytrends) (1.19.5)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->pytrends) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->pytrends) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->pytrends) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->pytrends) (2020.12.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.25->pytrends) (1.15.0)

In [ ]:
#import libraries to use
from pytrends.request import TrendReq
import pandas as pd
import time

In [ ]:

startTime = time.time()
pytrend = TrendReq(hl='en-US', tz=360)


colnames = ["keywords"] #from trends.csv dataset
df = pd.read_csv("trends.csv", names=colnames) #read dataset to get keywords to be used
df2 = df["keywords"].values.tolist()
df2.remove("Keywords")

def year(date):
  dataset = []
  for x in range(0,len(df2)):
     keywords = [df2[x]]
     pytrend.build_payload(
     kw_list=keywords,
     cat=0,
     timeframe=date,
     geo='')

In [ ]:
#get data from 2012-01-01 to 2012-09-01
year('2012-01-01 2012-09-01')
dataset = []
data = pytrend.interest_over_time()
if not data.empty:
          data = data.drop(labels=['isPartial'],axis='columns')
          dataset.append(data)
result = pd.concat(dataset, axis=1)
result.reset_index()

          date  bitcoins
0   2012-01-01        26
1   2012-01-02        20
2   2012-01-03         6
3   2012-01-04        25
4   2012-01-05        44
..         ...       ...
240 2012-08-28        34
241 2012-08-29        23
242 2012-08-30        69
243 2012-08-31        24
244 2012-09-01        35

[245 rows x 2 columns]

In [ ]:
#get data form 2012-09-02 to 2013-05-01
year('2012-09-02 2013-05-01')
dataset = []
data = pytrend.interest_over_time()
if not data.empty:
          data = data.drop(labels=['isPartial'],axis='columns')
          dataset.append(data)
result1 = pd.concat(dataset, axis=1)
result1.reset_index()

          date  bitcoins
0   2012-09-02         1
1   2012-09-03         5
2   2012-09-04         2
3   2012-09-05        12
4   2012-09-06        13
..         ...       ...
237 2013-04-27        21
238 2013-04-28        19
239 2013-04-29        13
240 2013-04-30        19
241 2013-05-01        18

[242 rows x 2 columns]

In [ ]:
#get data from 2013-05-02 to 2014-01-01
year('2013-05-02 2014-01-01')
dataset = []
data = pytrend.interest_over_time()
if not data.empty:
          data = data.drop(labels=['isPartial'],axis='columns')
          dataset.append(data)
result2 = pd.concat(dataset, axis=1)
result2.reset_index()

          date  bitcoins
0   2013-05-02        11
1   2013-05-03        10
2   2013-05-04         8
3   2013-05-05         8
4   2013-05-06        12
..         ...       ...
240 2013-12-28        18
241 2013-12-29        14
242 2013-12-30        15
243 2013-12-31        16
244 2014-01-01        12

[245 rows x 2 columns]

In [ ]:
#get data from 2014-01-02 to 2014-09-01
year('2014-01-02 2014-09-01')
dataset = []
data = pytrend.interest_over_time()
if not data.empty:
          data = data.drop(labels=['isPartial'],axis='columns')
          dataset.append(data)
result3 = pd.concat(dataset, axis=1)
result3.reset_index()

          date  bitcoins
0   2014-01-02        42
1   2014-01-03        46
2   2014-01-04        40
3   2014-01-05        48
4   2014-01-06        58
..         ...       ...
238 2014-08-28        14
239 2014-08-29        20
240 2014-08-30        11
241 2014-08-31        17
242 2014-09-01        20

[243 rows x 2 columns]

In [ ]:
#get data from 2014-09-02 to 2015-05-01
year('2014-09-02 2015-05-01')
dataset = []
data = pytrend.interest_over_time()
if not data.empty:
          data = data.drop(labels=['isPartial'],axis='columns')
          dataset.append(data)
result4 = pd.concat(dataset, axis=1)
result4.reset_index()

          date  bitcoins
0   2014-09-02        69
1   2014-09-03        70
2   2014-09-04        68
3   2014-09-05        74
4   2014-09-06        71
..         ...       ...
237 2015-04-27        43
238 2015-04-28        61
239 2015-04-29        42
240 2015-04-30        52
241 2015-05-01        42

[242 rows x 2 columns]

In [ ]:
#get data from 2015-05-02 to 2016-01-01
year('2015-05-02 2016-01-01')
dataset = []
data = pytrend.interest_over_time()
if not data.empty:
          data = data.drop(labels=['isPartial'],axis='columns')
          dataset.append(data)
result5 = pd.concat(dataset, axis=1)
result5.reset_index()

          date  bitcoins
0   2015-05-02        25
1   2015-05-03        23
2   2015-05-04        31
3   2015-05-05        34
4   2015-05-06        21
..         ...       ...
240 2015-12-28        45
241 2015-12-29        26
242 2015-12-30        36
243 2015-12-31        24
244 2016-01-01        31

[245 rows x 2 columns]

In [ ]:
#get data from 2016-01-02 to 2016-09-01
year('2016-01-02 2016-09-01')
dataset = []
data = pytrend.interest_over_time()
if not data.empty:
          data = data.drop(labels=['isPartial'],axis='columns')
          dataset.append(data)
result5 = pd.concat(dataset, axis=1)
result5.reset_index()

          date  bitcoins
0   2016-01-02        47
1   2016-01-03        34
2   2016-01-04        76
3   2016-01-05        47
4   2016-01-06        38
..         ...       ...
239 2016-08-28        51
240 2016-08-29        43
241 2016-08-30        49
242 2016-08-31        49
243 2016-09-01        45

[244 rows x 2 columns]

In [ ]:
#get data from 2016-09-02 to 2017-05-01
year('2016-09-02 2017-05-01')
dataset = []
data = pytrend.interest_over_time()
if not data.empty:
          data = data.drop(labels=['isPartial'],axis='columns')
          dataset.append(data)
result6 = pd.concat(dataset, axis=1)
result6.reset_index()

          date  bitcoins
0   2016-09-02        35
1   2016-09-03        41
2   2016-09-04        59
3   2016-09-05        41
4   2016-09-06        58
..         ...       ...
237 2017-04-27        76
238 2017-04-28        72
239 2017-04-29        59
240 2017-04-30        62
241 2017-05-01        65

[242 rows x 2 columns]

In [ ]:
#get data from 2017-05-02 to 2018-01-01
year('2017-05-02 2018-01-01')
dataset = []
data = pytrend.interest_over_time()
if not data.empty:
          data = data.drop(labels=['isPartial'],axis='columns')
          dataset.append(data)
result7 = pd.concat(dataset, axis=1)
result7.reset_index()

          date  bitcoins
0   2017-05-02         9
1   2017-05-03         8
2   2017-05-04        10
3   2017-05-05        10
4   2017-05-06         8
..         ...       ...
240 2017-12-28        30
241 2017-12-29        27
242 2017-12-30        26
243 2017-12-31        24
244 2018-01-01        23

[245 rows x 2 columns]

In [ ]:
#get data from 2018-01-02 to 2018-09-01
year('2018-01-02 2018-09-01')
dataset = []
data = pytrend.interest_over_time()
if not data.empty:
          data = data.drop(labels=['isPartial'],axis='columns')
          dataset.append(data)
result8 = pd.concat(dataset, axis=1)
result8.reset_index()

          date  bitcoins
0   2018-01-02        88
1   2018-01-03        94
2   2018-01-04        89
3   2018-01-05       100
4   2018-01-06        77
..         ...       ...
238 2018-08-28        15
239 2018-08-29        20
240 2018-08-30        21
241 2018-08-31        17
242 2018-09-01        12

[243 rows x 2 columns]

In [ ]:
#get data from 2018-09-02 to 2019-05-01
year('2018-09-02 2019-05-01')
dataset = []
data = pytrend.interest_over_time()
if not data.empty:
          data = data.drop(labels=['isPartial'],axis='columns')
          dataset.append(data)
result9 = pd.concat(dataset, axis=1)
result9.reset_index()

          date  bitcoins
0   2018-09-02        60
1   2018-09-03        67
2   2018-09-04        57
3   2018-09-05        79
4   2018-09-06        76
..         ...       ...
237 2019-04-27        59
238 2019-04-28        42
239 2019-04-29        50
240 2019-04-30        55
241 2019-05-01        41

[242 rows x 2 columns]

In [ ]:
#get data from 2019-05-02 to 2020-01-01
year('2019-05-02 2020-01-01')
dataset = []
data = pytrend.interest_over_time()
if not data.empty:
          data = data.drop(labels=['isPartial'],axis='columns')
          dataset.append(data)
result10 = pd.concat(dataset, axis=1)
result10.reset_index()

          date  bitcoins
0   2019-05-02        27
1   2019-05-03        40
2   2019-05-04        30
3   2019-05-05        38
4   2019-05-06        44
..         ...       ...
240 2019-12-28        42
241 2019-12-29        30
242 2019-12-30        33
243 2019-12-31        21
244 2020-01-01        39

[245 rows x 2 columns]

In [ ]:
#get data from 2020-01-02 to 2020-05-01
year('2020-01-02 2020-05-01')
dataset = []
data = pytrend.interest_over_time()
if not data.empty:
          data = data.drop(labels=['isPartial'],axis='columns')
          dataset.append(data)
result11 = pd.concat(dataset, axis=1)
result11.reset_index()

          date  bitcoins
0   2020-01-02        58
1   2020-01-03        49
2   2020-01-04        39
3   2020-01-05        43
4   2020-01-06        55
..         ...       ...
116 2020-04-27        59
117 2020-04-28        57
118 2020-04-29        95
119 2020-04-30        90
120 2020-05-01        83

[121 rows x 2 columns]

In [ ]:
#get data from 2020-05-02 to 2021-01-01
year('2020-05-02 2021-01-01')
dataset = []
data = pytrend.interest_over_time()
if not data.empty:
          data = data.drop(labels=['isPartial'],axis='columns')
          dataset.append(data)
result12 = pd.concat(dataset, axis=1)
result12.reset_index()

          date  bitcoins
0   2020-05-02        37
1   2020-05-03        37
2   2020-05-04        52
3   2020-05-05        44
4   2020-05-06        41
..         ...       ...
240 2020-12-28       100
241 2020-12-29        69
242 2020-12-30        80
243 2020-12-31        59
244 2021-01-01        64

[245 rows x 2 columns]

In [ ]:
#get data from 2021-01-02 to 2021-04-15
year('2021-01-02 2021-04-15')
dataset = []
data = pytrend.interest_over_time()
if not data.empty:
          data = data.drop(labels=['isPartial'],axis='columns')
          dataset.append(data)
result12 = pd.concat(dataset, axis=1)
result12.reset_index()

          date  bitcoins
0   2021-01-02        68
1   2021-01-03        78
2   2021-01-04        58
3   2021-01-05        72
4   2021-01-06        65
..         ...       ...
96  2021-04-08        37
97  2021-04-09        50
98  2021-04-10        35
99  2021-04-11        34
100 2021-04-12        36

[101 rows x 2 columns]

In [ ]:
#concat the all data of different dates to one data 
frames = [result,result1, result2, result3,result4,result5,result6,result7,
          result8,result9,result10,result11,result12]
df_trends = pd.concat(frames)
df_trends.reset_index()

           date  bitcoins
0    2012-01-01        26
1    2012-01-02        20
2    2012-01-03         6
3    2012-01-04        25
4    2012-01-05        44
...         ...       ...
2895 2021-04-08        37
2896 2021-04-09        50
2897 2021-04-10        35
2898 2021-04-11        34
2899 2021-04-12        36

[2900 rows x 2 columns]

In [ ]:
#save data into csv
df_trends.to_csv('df_trends.csv')